# Generated by Django 5.0.6 on 2025-02-18 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='mainapp.event', verbose_name='Match'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.PositiveIntegerField(verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Propriétaire'),
        ),
    ]
